export const data = [
    {
        id: "1",
        nombre: "MAXIMIZE",
        categoria: 'A',
        image:'https://picsum.photos/200/150',
        descripcion: "Bioestimulante de algas + AA + Micros",
        precio: 1000,
    },
    {
        id: "2",
        nombre: "AMINO 26",
        categoria: "B",
        image:'https://picsum.photos/200/150',
        descripcion: "AA de origen vegetal + Materia Orgánica",
        precio: 2000,
    },
    {
        id: "3",
        nombre: "CUPRUM",
        categoria:"C",
        image:'https://picsum.photos/200/150',
        descripcion: "Biocontrol y nutrición",
        precio: 3000,
    },
    {
        id: "4",
        nombre: "EFFIK ONE",
        categoria:"A",
        image:'https://picsum.photos/200/150',
        descripcion: "Nutrición y Quimioterapia vegetal",
        precio: 4000,
    },
    {
        id: "5",
        nombre: "CABZN PLUS",
        categoria:"B",
        image:'https://picsum.photos/200/150',
        descripcion: "Fisiorresolutivo",
        precio: 5000,
    },
    {
        id:"6",
        nombre:"H 62 PLUS",
        categoria:"C",
        image:'https://picsum.photos/200/150',
        descripcion:"Fisiorresolutivo. Macronutriente. Anticongelante",
        precio: 6000,
    },
];