export const data = [
    {
        id: "1",
        nombre: "MAXIMIZE",
        categoria: 'A',
        image:'https://picsum.photos/400/300',
        descripcion: "Bioestimulante de algas + AA + Micros",
        precio: 1000,
    },
    {
        id: "2",
        nombre: "AMINO 26",
        categoria: "A",
        image:'https://picsum.photos/400/300',
        descripcion: "AA de origen vegetal + Materia Orgánica",
        precio: 2000,
    },
    {
        id: "3",
        nombre: "CUPRUM",
        categoria:"A",
        image:'https://picsum.photos/400/300',
        descripcion: "Biocontrol y nutrición",
        precio: 3000,
    },
    {
        id: "4",
        nombre: "EFFIK ONE",
        categoria:"A",
        image:'https://picsum.photos/400/300',
        descripcion: "Nutrición y Quimioterapia vegetal",
        precio: 4000,
    },
    {
        id: "5",
        nombre: "CABZN PLUS",
        categoria:"B",
        image:'https://picsum.photos/400/300',
        descripcion: "Fisiorresolutivo",
        precio: 5000,
    },
    {
        id:"6",
        nombre:"K 62 PLUS",
        categoria:"B",
        image:'https://picsum.photos/400/300',
        descripcion:"Fisiorresolutivo. Macronutriente. Anticongelante",
        precio: 6000,
    },
    {
        id:"7",
        nombre:"N CONTROL",
        categoria:"B",
        image:'https://picsum.photos/400/300',
        descripcion:"Fertilizante Nitrogenado de liberación controlada",
        precio: 7000,
    },
    {
        id:"8",
        nombre:"PHOSK 60 PLUS",
        categoria:"B",
        image:'https://picsum.photos/400/300',
        descripcion:"Fisiorresolutivo. Inductor SAR con algas, AA, MO y Micros",
        precio: 8000,
    },
    {
        id:"9",
        nombre:"RIPENING BRIX",
        categoria:"C",
        image:'https://picsum.photos/400/300',
        descripcion:"Nutriciín especial. Producctiones de Calidad",
        precio: 9000,
    },
    {
        id:"10",
        nombre:"APTUS",
        categoria:"C",
        image:'https://picsum.photos/400/300',
        descripcion:"NPK + Micros",
        precio: 10000,
    },
    {
        id:"11",
        nombre:"OLIGA",
        categoria:"C",
        image:'https://picsum.photos/400/300',
        descripcion:"NPK + Micros",
        precio: 11000,
    },
    {
        id:"12",
        nombre:"BORO PLUS",
        categoria:"C",
        image:'https://picsum.photos/400/300',
        descripcion:"NPK + Micros + AA",
        precio: 12000,
    },
];